### ISSUE TITLE
Merging comments outside of single and comments_template

### ISSUE THREAD

**Issue by Lindfyrsten** [senlin/multilingual-comments-wpml#4]
Trying to show comments for every post on archive using:
```
$comments = get_comments(array(
                'post_id' => get_the_ID(),
                'status' => 'approve'
));
```
This only gets me the current language comments. Is the plugin only supposed to work when on a single template?

**Comment by senlin** [comment]
Hello, yes the plugin works for the single template which is where it gets the post ID of the other language(s).

**Comment by Lindfyrsten** [comment]
Can I get the other ID's outside of single if I have one of the ID's?

In other words: Is it at all possible to merge outside of single?

**Comment by senlin** [comment]
> Can I get the other ID's outside of single if I have one of the ID's?

In theory yes.

I'm not sure if it is possible at all as it will get a bit more complicated. One can always try though.

**Comment by Lindfyrsten** [comment]
Here is the solution if anyone is looking to do the same:

```
foreach ($languages as $code => $l) {
                if (!$l['active']) {
                    $otherID = apply_filters('wpml_object_id', $post_ID, $type, false, $l['language_code']);
                    if ($otherID) {
                        // Switch language
                        $sitepress->switch_lang($l['language_code']);
                        $post = get_post($otherID);
                        $othercomments = get_comments(array(
                            'post_id' => $otherID,
                            'status' => 'approve',
                            'order' => 'ASC'
                        ));
                        $comments = array_merge($comments, $othercomments);
                    }
                }
            }
```
Just like your plugin code, except with the addition of switch_lang.
Programatically switching language to the language code made it work.

Also if I may suggest adding if ($otherID) logic to multilingual-comments-wpml.php
I ran into an error where a post wasn't duplicated and it would show ALL comments from current language code because $otherID would return null.

Adding that check prevents that from happening:

```
	public function merge_comments($comments, $post_ID)
	{
		global $sitepress;

		remove_filter('comments_clauses', array($sitepress, 'comments_clauses'));

		$languages = apply_filters('wpml_active_languages', null, 'skip_missing=1');

		$post = get_post($post_ID);
		$type = $post->post_type;

		foreach ($languages as $code => $l) {
			if (!$l['active']) {
				$otherID = apply_filters('wpml_object_id', $post_ID, $type, false, $l['language_code']);
				if ($otherID) {
					$othercomments = get_comments(array('post_id' => $otherID, 'status' => 'approve', 'order' => 'ASC'));
					$comments = array_merge($comments, $othercomments);
				}
			}
		}

		if ($languages) {
			usort($comments, [$this, 'sort_merged_comments']);
		}

		add_filter('comments_clauses', array($sitepress, 'comments_clauses'), 10, 2);

		return $comments;
	}
```

**Comment by senlin** [comment]
Thank you for the suggestion! I will add it to the source code (or if you want you can do a PR) sometime soon :)
